services:
  kfet:
    build:
      context: /mnt/Sites/kfet
      dockerfile: Dockerfile
    container_name: kfet-app
    restart: unless-stopped
    ports:
      - "30083:3000"
    volumes:
      - /mnt/Sites/kfet/data:/app/data
